name: crv_keras
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - joblib=0.14.1
  - lightgbm=2.3.1
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.1.3
  - psutil=5.6.7
  - pyarrow=0.15.1
  - python=3.7.6
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - tensorflow-gpu=2.0.0
